image: "python:latest"

stages:
  - testing

run_static:
  stage: testing
  before_script:
    - pip install pylint
  script:
    - pylint src/
  
run_tests:
  stage: testing
  before_script:
    - pip install pytest pytest-cov
  script:
    - python3 -m pytest --cov-report=html --cov=src .
  artifacts:
    paths: 
      - coverage
    expire_in: 30 days
